// <auto-generated />
using AnimalShelterAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelterAPI.Migrations
{
    [DbContext(typeof(AnimalShelterAPIContext))]
    partial class AnimalShelterAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("AnimalShelterAPI.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Species")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 13,
                            Description = "sweet old granny",
                            Gender = "Female",
                            Name = "Doggy",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 8,
                            Description = "people pleaser",
                            Gender = "Male",
                            Name = "Dax",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 4,
                            Description = "big teddy bear",
                            Gender = "Male",
                            Name = "Bruce",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 6,
                            Description = "explorer",
                            Gender = "Female",
                            Name = "Kiki",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 7,
                            Description = "hates crowds",
                            Gender = "Female",
                            Name = "Pepper",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 6,
                            Description = "super friendly",
                            Gender = "Female",
                            Name = "Ramona",
                            Species = "Cat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
